name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test Frontend (Ionic Angular)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm dependencies
        run: npm install

      - name: Run Angular tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Run Lint
        run: npm run lint

      - name: Build Ionic app
        run: npm run build
